### ISSUE TITLE
Closing 'source' tags being added to videos

### ISSUE THREAD

**Issue by diegocanal** [mtoensing/lazy-loading-responsive-images#37] opened 2020-01-09 10:52 UTC
Hi Florian!

It seems that the plugin is adding `</source>` tags inside the `<video>` element. Please notice that `<source>` is a HTML empty element (we should never use a `</source>` closing tag). [Reference in Mozilla Developer Network](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source).

It happens even if I disable the 'Enable lazy loading for videos' option.

The original code (with Lazy Loader inactive) :

```
	<video class="mbn" controls poster="https://www.mydomain.com/wp-content/uploads/videos/video-file-name.jpg">
	  <source src="https://www.mydomain.com/wp-content/uploads/videos/video-file-name.webm" type="video/webm">
	  <source src="https://www.mydomain.com/wp-content/uploads/videos/video-file-name.mp4" type="video/mp4">
	  <source src="https://www.mydomain.com/wp-content/uploads/videos/video-file-name.ogv" type="video/ogg">
	</video>
```

When Lazy Loader is active –with or without the 'Enable lazy loading for videos' option enabled– that code is output with those 3 `</source>` tags added at the end:

```
		<noscript><VIDEO class="mbn" controls="" poster="https://www.mydomain.com/wp-content/uploads/videos/video-file-name.jpg"></VIDEO></noscript>
<video class="mbn lazyload" controls data-poster="https://www.mydomain.com/wp-content/uploads/videos/video-file-name.jpg" preload="none">
	  <source src="https://www.mydomain.com/wp-content/uploads/videos/video-file-name.webm" type="video/webm">
	  <source src="https://www.mydomain.com/wp-content/uploads/videos/video-file-name.mp4" type="video/mp4">
	  <source src="https://www.mydomain.com/wp-content/uploads/videos/video-file-name.ogv" type="video/ogg">
	</source></source></source></video>
```

**Comment by florianbrinkmann** [comment] 2020-01-09 11:32
Hi Diego,

thanks for opening the issue! I will take a look at it. Maybe I need to search another DOM parser, maybe the reason for the closing tags is, that `DOMDocument` does not know HTML5 elements…

Best,
Florian

**Comment by diegocanal** [comment] 2020-01-09 11:44
Thanks Florian. In the meantime, can you think of any temporary fix to isolate the video elements so they are not affected by Lazy Loader?

**Comment by florianbrinkmann** [comment] 2020-01-09 11:47
Unfortunately no. The script parses the complete markup of the content, and there is no way to exclude something from not being parsed… I will try to find a fix for that tonight

**Comment by diegocanal** [comment] 2020-01-09 12:29
Great! Thanks a lot.

**Comment by florianbrinkmann** [comment] 2020-01-10 06:56
You're welcome. I had issues with installing a composer package yesterday, so no luck with finding a solution. I will try again at the weekend.

**Comment by diegocanal** [comment] 2020-01-10 07:20
Thanks for keeping us posted!

**Comment by florianbrinkmann** [comment] 2020-01-13 08:30
I think I might have found a solution. I will try to release a beta later today.

**Comment by diegocanal** [comment] 2020-01-13 08:31
Great news! Thank you.

**Comment by florianbrinkmann** [comment] 2020-01-14 14:51
Hi @diegocanal,

could you give the beta a try (https://github.com/florianbrinkmann/lazy-loading-responsive-images/releases/tag/v6.0.0-beta.3 – the lazy-loading-responsive-images.zip) and check if it fixes the issue?

Thanks,
Florian

**Comment by florianbrinkmann** [comment] 2020-01-14 14:52
PS: the new version needs PHP 7 or newer.

**Comment by florianbrinkmann** [comment] 2020-01-14 15:57
While trying to reproduce the issue in #22, I found a bug with the beta 3, that adds an additional  `html` element when the plugin `filter_markup()` is called directly and the option for complete markup processing is enabled. Fixed that with beta 4: https://github.com/florianbrinkmann/lazy-loading-responsive-images/releases/tag/v6.0.0-beta.4

**Comment by diegocanal** [comment] 2020-01-14 16:35
Hi @florianbrinkmann ,

v6.0.0-beta.4 seems to fix the issue.

I see yo changed the DOM parser to masterminds/html5, right?

Thank you!

**Comment by florianbrinkmann** [comment] 2020-01-15 10:23
Hi @diegocanal,

you’re welcome, thanks for testing, great to hear that it works!

> I see yo changed the DOM parser to masterminds/html5, right?

Yes :)

Best,
Florian

**Closed as completed by florianbrinkmann** 2020-01-15 10:23 UTC
Labels: bug
